from __future__ import annotations

from pathlib import Path

FILES = {'asbp/template_selection.py': 'from __future__ import annotations\n'
                               '\n'
                               'from asbp.document_template_model import (\n'
                               '    DocumentTemplateLibraryModel,\n'
                               '    DocumentTemplateRecordModel,\n'
                               ')\n'
                               'from asbp.document_template_store import (\n'
                               '    get_document_template_by_id,\n'
                               '    load_default_document_template_library,\n'
                               ')\n'
                               'from asbp.mapping_source_model import MappingLibraryModel\n'
                               'from asbp.mapping_source_store import '
                               'load_default_mapping_library\n'
                               'from asbp.template_selection_model import (\n'
                               '    REQUIRED_TEMPLATE_SELECTION_NON_IMPLEMENTATION_CLAIMS,\n'
                               '    TemplateSelectionCandidateRejectionModel,\n'
                               '    TemplateSelectionInputModel,\n'
                               '    TemplateSelectionResultModel,\n'
                               ')\n'
                               '\n'
                               '\n'
                               'def select_template_for_request(\n'
                               '    request: TemplateSelectionInputModel,\n'
                               '    *,\n'
                               '    template_library: DocumentTemplateLibraryModel | None = None,\n'
                               '    mapping_library: MappingLibraryModel | None = None,\n'
                               ') -> TemplateSelectionResultModel:\n'
                               '    template_library = template_library or '
                               'load_default_document_template_library()\n'
                               '    mapping_library = mapping_library or '
                               'load_default_mapping_library()\n'
                               '\n'
                               '    mapped_template_ids, source_mapping_ids = '
                               'collect_template_ids_from_standard_mappings(\n'
                               '        mapping_library,\n'
                               '        request.standards_bundle_refs,\n'
                               '    )\n'
                               '\n'
                               '    matched_templates: list[DocumentTemplateRecordModel] = []\n'
                               '    rejected_candidates: '
                               'list[TemplateSelectionCandidateRejectionModel] = []\n'
                               '\n'
                               '    for template in template_library.template_records:\n'
                               '        rejection = _first_rejection_for_template(\n'
                               '            template,\n'
                               '            request,\n'
                               '            mapped_template_ids,\n'
                               '        )\n'
                               '        if rejection is not None:\n'
                               '            rejected_candidates.append(rejection)\n'
                               '            continue\n'
                               '\n'
                               '        matched_templates.append(template)\n'
                               '\n'
                               '    candidate_template_ids = [template.template_id for template in '
                               'matched_templates]\n'
                               '\n'
                               '    if len(matched_templates) == 1:\n'
                               '        selected_template = matched_templates[0]\n'
                               '        return TemplateSelectionResultModel(\n'
                               '            selection_id=request.selection_id,\n'
                               '            status="selected",\n'
                               '            selected_template_id=selected_template.template_id,\n'
                               '            candidate_template_ids=candidate_template_ids,\n'
                               '            rejected_candidates=rejected_candidates,\n'
                               '            source_mapping_ids=source_mapping_ids,\n'
                               '            decision_reason=(\n'
                               '                "Selected deterministic template record by '
                               'document family, "\n'
                               '                "document type, standards-bundle compatibility, '
                               'standards-to-template "\n'
                               '                "mapping where available, intake route, and active '
                               'lifecycle status."\n'
                               '            ),\n'
                               '            explicit_non_implementation_claims=sorted(\n'
                               '                '
                               'REQUIRED_TEMPLATE_SELECTION_NON_IMPLEMENTATION_CLAIMS\n'
                               '            ),\n'
                               '        )\n'
                               '\n'
                               '    if not matched_templates:\n'
                               '        return TemplateSelectionResultModel(\n'
                               '            selection_id=request.selection_id,\n'
                               '            status="no_match",\n'
                               '            candidate_template_ids=[],\n'
                               '            rejected_candidates=rejected_candidates,\n'
                               '            source_mapping_ids=source_mapping_ids,\n'
                               '            decision_reason="No deterministic template matched the '
                               'request constraints.",\n'
                               '            explicit_non_implementation_claims=sorted(\n'
                               '                '
                               'REQUIRED_TEMPLATE_SELECTION_NON_IMPLEMENTATION_CLAIMS\n'
                               '            ),\n'
                               '        )\n'
                               '\n'
                               '    return TemplateSelectionResultModel(\n'
                               '        selection_id=request.selection_id,\n'
                               '        status="ambiguous",\n'
                               '        candidate_template_ids=candidate_template_ids,\n'
                               '        rejected_candidates=rejected_candidates,\n'
                               '        source_mapping_ids=source_mapping_ids,\n'
                               '        decision_reason="Multiple deterministic template records '
                               'matched the request constraints.",\n'
                               '        explicit_non_implementation_claims=sorted(\n'
                               '            REQUIRED_TEMPLATE_SELECTION_NON_IMPLEMENTATION_CLAIMS\n'
                               '        ),\n'
                               '    )\n'
                               '\n'
                               '\n'
                               'def load_template_for_request(\n'
                               '    request: TemplateSelectionInputModel,\n'
                               '    *,\n'
                               '    template_library: DocumentTemplateLibraryModel | None = None,\n'
                               '    mapping_library: MappingLibraryModel | None = None,\n'
                               ') -> DocumentTemplateRecordModel:\n'
                               '    template_library = template_library or '
                               'load_default_document_template_library()\n'
                               '    result = select_template_for_request(\n'
                               '        request,\n'
                               '        template_library=template_library,\n'
                               '        mapping_library=mapping_library,\n'
                               '    )\n'
                               '\n'
                               '    if result.status != "selected" or result.selected_template_id '
                               'is None:\n'
                               '        raise ValueError(\n'
                               '            "Template selection did not resolve to exactly one '
                               'template: "\n'
                               '            f"{result.status}"\n'
                               '        )\n'
                               '\n'
                               '    return get_document_template_by_id(template_library, '
                               'result.selected_template_id)\n'
                               '\n'
                               '\n'
                               'def collect_template_ids_from_standard_mappings(\n'
                               '    mapping_library: MappingLibraryModel,\n'
                               '    standards_bundle_refs: list[str],\n'
                               ') -> tuple[set[str], list[str]]:\n'
                               '    if not standards_bundle_refs:\n'
                               '        return set(), []\n'
                               '\n'
                               '    requested_standard_refs = set(standards_bundle_refs)\n'
                               '    template_ids: set[str] = set()\n'
                               '    source_mapping_ids: list[str] = []\n'
                               '\n'
                               '    for mapping in mapping_library.mappings:\n'
                               '        if mapping.mapping_kind != "standard_to_template":\n'
                               '            continue\n'
                               '\n'
                               '        mapping_standard_refs = {\n'
                               '            reference.reference_id\n'
                               '            for reference in mapping.source_refs\n'
                               '            if reference.reference_type == "standard_bundle"\n'
                               '            and reference.reference_status == "resolved_source"\n'
                               '        }\n'
                               '        if not '
                               'requested_standard_refs.issubset(mapping_standard_refs):\n'
                               '            continue\n'
                               '\n'
                               '        for reference in mapping.target_refs:\n'
                               '            if (\n'
                               '                reference.reference_type == "template"\n'
                               '                and reference.reference_status == '
                               '"resolved_source"\n'
                               '            ):\n'
                               '                template_ids.add(reference.reference_id)\n'
                               '\n'
                               '        source_mapping_ids.append(mapping.mapping_id)\n'
                               '\n'
                               '    return template_ids, source_mapping_ids\n'
                               '\n'
                               '\n'
                               'def _first_rejection_for_template(\n'
                               '    template: DocumentTemplateRecordModel,\n'
                               '    request: TemplateSelectionInputModel,\n'
                               '    mapped_template_ids: set[str],\n'
                               ') -> TemplateSelectionCandidateRejectionModel | None:\n'
                               '    if template.lifecycle_status != "active":\n'
                               '        return _build_rejection(\n'
                               '            template,\n'
                               '            "inactive_lifecycle_status",\n'
                               '            "Template record is not active.",\n'
                               '        )\n'
                               '\n'
                               '    if template.document_family_id != request.document_family_id:\n'
                               '        return _build_rejection(\n'
                               '            template,\n'
                               '            "document_family_mismatch",\n'
                               '            "Template document family does not match request.",\n'
                               '        )\n'
                               '\n'
                               '    if _normalize(template.document_type) != '
                               '_normalize(request.document_type):\n'
                               '        return _build_rejection(\n'
                               '            template,\n'
                               '            "document_type_mismatch",\n'
                               '            "Template document type does not match request.",\n'
                               '        )\n'
                               '\n'
                               '    requested_standards = set(request.standards_bundle_refs)\n'
                               '    template_standards = set(template.standards_bundle_refs)\n'
                               '    if requested_standards and not '
                               'requested_standards.issubset(template_standards):\n'
                               '        return _build_rejection(\n'
                               '            template,\n'
                               '            "standards_bundle_mismatch",\n'
                               '            "Template does not support all requested standards '
                               'bundle refs.",\n'
                               '        )\n'
                               '\n'
                               '    if mapped_template_ids and template.template_id not in '
                               'mapped_template_ids:\n'
                               '        return _build_rejection(\n'
                               '            template,\n'
                               '            "standards_mapping_mismatch",\n'
                               '            "Template is not linked by the resolved '
                               'standards-to-template mapping.",\n'
                               '        )\n'
                               '\n'
                               '    if request.intake_route_ref not in '
                               'template.intake_route_refs:\n'
                               '        return _build_rejection(\n'
                               '            template,\n'
                               '            "intake_route_mismatch",\n'
                               '            "Template does not support requested intake route.",\n'
                               '        )\n'
                               '\n'
                               '    return None\n'
                               '\n'
                               '\n'
                               'def _build_rejection(\n'
                               '    template: DocumentTemplateRecordModel,\n'
                               '    reason_code,\n'
                               '    message: str,\n'
                               ') -> TemplateSelectionCandidateRejectionModel:\n'
                               '    return TemplateSelectionCandidateRejectionModel(\n'
                               '        template_id=template.template_id,\n'
                               '        reason_code=reason_code,\n'
                               '        message=message,\n'
                               '    )\n'
                               '\n'
                               '\n'
                               'def _normalize(value: str) -> str:\n'
                               '    return " ".join(value.casefold().split())\n',
 'asbp/template_selection_model.py': 'from __future__ import annotations\n'
                                     '\n'
                                     'from typing import Literal\n'
                                     '\n'
                                     'from pydantic import BaseModel, ConfigDict, Field, '
                                     'field_validator, model_validator\n'
                                     '\n'
                                     '\n'
                                     'TemplateSelectionRequestStatus = '
                                     'Literal["deterministic_template_selection_request"]\n'
                                     'TemplateSelectionResultStatus = Literal["selected", '
                                     '"no_match", "ambiguous"]\n'
                                     'TemplateSelectionRejectionReason = Literal[\n'
                                     '    "inactive_lifecycle_status",\n'
                                     '    "document_family_mismatch",\n'
                                     '    "document_type_mismatch",\n'
                                     '    "standards_bundle_mismatch",\n'
                                     '    "standards_mapping_mismatch",\n'
                                     '    "intake_route_mismatch",\n'
                                     ']\n'
                                     'TemplateSelectionIntakeRoute = Literal["ROUTE-DCF", '
                                     '"ROUTE-SKIP-DCF"]\n'
                                     '\n'
                                     '\n'
                                     'REQUIRED_TEMPLATE_SELECTION_NON_IMPLEMENTATION_CLAIMS = {\n'
                                     '    "does_not_generate_documents",\n'
                                     '    "does_not_validate_document_input_schemas",\n'
                                     '    "does_not_render_or_export_documents",\n'
                                     '    "does_not_use_ai_to_choose_templates",\n'
                                     '}\n'
                                     '\n'
                                     '\n'
                                     'class TemplateSelectionInputModel(BaseModel):\n'
                                     '    model_config = ConfigDict(extra="forbid")\n'
                                     '\n'
                                     '    selection_id: str = Field(min_length=1, '
                                     'pattern=r"^TPLSEL-[A-Z0-9-]+@v[0-9]+$")\n'
                                     '    status: TemplateSelectionRequestStatus = '
                                     '"deterministic_template_selection_request"\n'
                                     '    document_family_id: str = Field(min_length=1, '
                                     'pattern=r"^DOCF-[A-Z0-9-]+$")\n'
                                     '    document_type: str = Field(min_length=1)\n'
                                     '    template_intent: str | None = Field(default=None, '
                                     'min_length=1)\n'
                                     '    selector_context_ref: str | None = Field(default=None, '
                                     'min_length=1)\n'
                                     '    profile_refs: list[str] = Field(default_factory=list)\n'
                                     '    standards_bundle_refs: list[str] = '
                                     'Field(default_factory=list)\n'
                                     '    task_document_mapping_refs: list[str] = '
                                     'Field(default_factory=list)\n'
                                     '    intake_route_ref: TemplateSelectionIntakeRoute\n'
                                     '    selection_controls: list[str] = Field(min_length=1)\n'
                                     '    explicit_non_implementation_claims: list[str] = '
                                     'Field(min_length=1)\n'
                                     '\n'
                                     '    @field_validator(\n'
                                     '        "profile_refs",\n'
                                     '        "standards_bundle_refs",\n'
                                     '        "task_document_mapping_refs",\n'
                                     '        "selection_controls",\n'
                                     '        "explicit_non_implementation_claims",\n'
                                     '    )\n'
                                     '    @classmethod\n'
                                     '    def validate_no_blank_list_values(cls, values: '
                                     'list[str]) -> list[str]:\n'
                                     '        for value in values:\n'
                                     '            if not value.strip():\n'
                                     '                raise ValueError("Blank template selection '
                                     'request value is not allowed")\n'
                                     '        return values\n'
                                     '\n'
                                     '    @model_validator(mode="after")\n'
                                     '    def validate_selection_input_boundary(self):\n'
                                     '        self._validate_standards_bundle_refs()\n'
                                     '        self._validate_required_non_implementation_claims()\n'
                                     '        return self\n'
                                     '\n'
                                     '    def _validate_standards_bundle_refs(self) -> None:\n'
                                     '        seen_refs: set[str] = set()\n'
                                     '\n'
                                     '        for bundle_ref in self.standards_bundle_refs:\n'
                                     '            if not bundle_ref.startswith("SB-") or "@" not '
                                     'in bundle_ref:\n'
                                     '                raise ValueError(\n'
                                     '                    "Template selection '
                                     'standards_bundle_refs must use SB-...@v... IDs: "\n'
                                     '                    f"{bundle_ref}"\n'
                                     '                )\n'
                                     '\n'
                                     '            if bundle_ref in seen_refs:\n'
                                     '                raise ValueError(\n'
                                     '                    "Duplicate template selection '
                                     'standards_bundle_ref is not allowed: "\n'
                                     '                    f"{bundle_ref}"\n'
                                     '                )\n'
                                     '            seen_refs.add(bundle_ref)\n'
                                     '\n'
                                     '    def _validate_required_non_implementation_claims(self) '
                                     '-> None:\n'
                                     '        provided_claims = '
                                     'set(self.explicit_non_implementation_claims)\n'
                                     '        missing_claims = sorted(\n'
                                     '            '
                                     'REQUIRED_TEMPLATE_SELECTION_NON_IMPLEMENTATION_CLAIMS - '
                                     'provided_claims\n'
                                     '        )\n'
                                     '\n'
                                     '        if missing_claims:\n'
                                     '            raise ValueError(\n'
                                     '                "M29.3 template selection request is missing '
                                     'explicit "\n'
                                     '                f"non-implementation claims: {\', '
                                     '\'.join(missing_claims)}"\n'
                                     '            )\n'
                                     '\n'
                                     '\n'
                                     'class TemplateSelectionCandidateRejectionModel(BaseModel):\n'
                                     '    model_config = ConfigDict(extra="forbid")\n'
                                     '\n'
                                     '    template_id: str = Field(min_length=1, '
                                     'pattern=r"^TPL-[A-Z0-9-]+@v[0-9]+$")\n'
                                     '    reason_code: TemplateSelectionRejectionReason\n'
                                     '    message: str = Field(min_length=1)\n'
                                     '\n'
                                     '\n'
                                     'class TemplateSelectionResultModel(BaseModel):\n'
                                     '    model_config = ConfigDict(extra="forbid")\n'
                                     '\n'
                                     '    selection_id: str = Field(min_length=1, '
                                     'pattern=r"^TPLSEL-[A-Z0-9-]+@v[0-9]+$")\n'
                                     '    status: TemplateSelectionResultStatus\n'
                                     '    selected_template_id: str | None = Field(\n'
                                     '        default=None,\n'
                                     '        pattern=r"^TPL-[A-Z0-9-]+@v[0-9]+$",\n'
                                     '    )\n'
                                     '    candidate_template_ids: list[str] = '
                                     'Field(default_factory=list)\n'
                                     '    rejected_candidates: '
                                     'list[TemplateSelectionCandidateRejectionModel] = Field(\n'
                                     '        default_factory=list\n'
                                     '    )\n'
                                     '    source_mapping_ids: list[str] = '
                                     'Field(default_factory=list)\n'
                                     '    decision_reason: str | None = Field(default=None, '
                                     'min_length=1)\n'
                                     '    explicit_non_implementation_claims: list[str] = '
                                     'Field(min_length=1)\n'
                                     '\n'
                                     '    @field_validator(\n'
                                     '        "candidate_template_ids",\n'
                                     '        "source_mapping_ids",\n'
                                     '        "explicit_non_implementation_claims",\n'
                                     '    )\n'
                                     '    @classmethod\n'
                                     '    def validate_no_blank_result_values(cls, values: '
                                     'list[str]) -> list[str]:\n'
                                     '        for value in values:\n'
                                     '            if not value.strip():\n'
                                     '                raise ValueError("Blank template selection '
                                     'result value is not allowed")\n'
                                     '        return values\n'
                                     '\n'
                                     '    @model_validator(mode="after")\n'
                                     '    def validate_selection_result_boundary(self):\n'
                                     '        self._validate_status_shape()\n'
                                     '        self._validate_unique_candidate_ids()\n'
                                     '        self._validate_required_non_implementation_claims()\n'
                                     '        return self\n'
                                     '\n'
                                     '    def _validate_status_shape(self) -> None:\n'
                                     '        if self.status == "selected":\n'
                                     '            if self.selected_template_id is None:\n'
                                     '                raise ValueError("Selected template result '
                                     'requires selected_template_id")\n'
                                     '            if self.decision_reason is None:\n'
                                     '                raise ValueError("Selected template result '
                                     'requires decision_reason")\n'
                                     '            if self.selected_template_id not in '
                                     'self.candidate_template_ids:\n'
                                     '                raise ValueError(\n'
                                     '                    "Selected template must be included in '
                                     'candidate_template_ids: "\n'
                                     '                    f"{self.selected_template_id}"\n'
                                     '                )\n'
                                     '            return\n'
                                     '\n'
                                     '        if self.selected_template_id is not None:\n'
                                     '            raise ValueError(\n'
                                     '                "No-match or ambiguous template selection '
                                     'result cannot include "\n'
                                     '                f"selected_template_id: '
                                     '{self.selected_template_id}"\n'
                                     '            )\n'
                                     '\n'
                                     '    def _validate_unique_candidate_ids(self) -> None:\n'
                                     '        if len(set(self.candidate_template_ids)) != '
                                     'len(self.candidate_template_ids):\n'
                                     '            raise ValueError("Duplicate '
                                     'candidate_template_ids are not allowed")\n'
                                     '\n'
                                     '    def _validate_required_non_implementation_claims(self) '
                                     '-> None:\n'
                                     '        provided_claims = '
                                     'set(self.explicit_non_implementation_claims)\n'
                                     '        missing_claims = sorted(\n'
                                     '            '
                                     'REQUIRED_TEMPLATE_SELECTION_NON_IMPLEMENTATION_CLAIMS - '
                                     'provided_claims\n'
                                     '        )\n'
                                     '\n'
                                     '        if missing_claims:\n'
                                     '            raise ValueError(\n'
                                     '                "M29.3 template selection result is missing '
                                     'explicit "\n'
                                     '                f"non-implementation claims: {\', '
                                     '\'.join(missing_claims)}"\n'
                                     '            )\n',
 'docs/milestones/M29/M29_3_TEMPLATE_SELECTION_LOADING.md': '---\n'
                                                            'doc_type: milestone_evidence_record\n'
                                                            'canonical_name: '
                                                            'M29_3_TEMPLATE_SELECTION_LOADING\n'
                                                            'status: '
                                                            'READY_FOR_USER_APPLICATION_VALIDATION_PENDING\n'
                                                            'phase: Phase 9 — Roadmap Reset and '
                                                            'Local Integrated CQV Product Core\n'
                                                            'milestone: M29\n'
                                                            'checkpoint: M29.3\n'
                                                            'checkpoint_title: Template '
                                                            'selection/loading\n'
                                                            'execution_mode: Build/content\n'
                                                            'application_mode: '
                                                            'user_applied_package\n'
                                                            'live_repo_write: NO\n'
                                                            '---\n'
                                                            '\n'
                                                            '# M29.3 — Template Selection / '
                                                            'Loading\n'
                                                            '\n'
                                                            '## Purpose\n'
                                                            '\n'
                                                            'M29.3 implements deterministic '
                                                            'template selection and loading for '
                                                            'the local integrated CQV document '
                                                            'factory path.\n'
                                                            '\n'
                                                            'This checkpoint consumes the '
                                                            'controlled template source records '
                                                            'implemented in M29.2 and resolves '
                                                            'exactly one template record when the '
                                                            'request constraints are '
                                                            'deterministic.\n'
                                                            '\n'
                                                            'M29.3 does not implement document '
                                                            'input schema validation, controlled '
                                                            'drafting, standards-backed output '
                                                            'generation, rendering/export, '
                                                            'lifecycle workflow, review/approval '
                                                            'workflow, UI/API behavior, AI/runtime '
                                                            'behavior, deployment, productization, '
                                                            'or SaaS readiness.\n'
                                                            '\n'
                                                            '## Implementation Assets\n'
                                                            '\n'
                                                            'The M29.3 user-applied package adds:\n'
                                                            '\n'
                                                            '- `asbp/template_selection_model.py`\n'
                                                            '- `asbp/template_selection.py`\n'
                                                            '- '
                                                            '`tests/test_template_selection_model.py`\n'
                                                            '- `tests/test_template_selection.py`\n'
                                                            '\n'
                                                            '## Implemented Behavior\n'
                                                            '\n'
                                                            'The package implements deterministic '
                                                            'template selection based on:\n'
                                                            '\n'
                                                            '1. document family;\n'
                                                            '2. document type;\n'
                                                            '3. standards-bundle compatibility;\n'
                                                            '4. resolved standards-to-template '
                                                            'mappings where standards bundle refs '
                                                            'are supplied;\n'
                                                            '5. intake route compatibility;\n'
                                                            '6. active template lifecycle status.\n'
                                                            '\n'
                                                            'The package returns visible '
                                                            'non-selected outcomes when:\n'
                                                            '\n'
                                                            '- no template matches the request '
                                                            'constraints;\n'
                                                            '- multiple templates match the '
                                                            'request constraints;\n'
                                                            '- the requested standards bundle is '
                                                            'unsupported;\n'
                                                            '- the requested intake route is '
                                                            'unsupported;\n'
                                                            '- a matching template record is '
                                                            'inactive or retired.\n'
                                                            '\n'
                                                            '## Source Boundaries\n'
                                                            '\n'
                                                            'M29.3 uses existing source truth '
                                                            'from:\n'
                                                            '\n'
                                                            '- `asbp/document_template_store.py`\n'
                                                            '- '
                                                            '`data/source/document_templates/starter_document_templates.json`\n'
                                                            '- `asbp/mapping_source_store.py`\n'
                                                            '- '
                                                            '`data/source/mappings/starter_mappings.json`\n'
                                                            '\n'
                                                            'M29.3 does not create new template '
                                                            'records and does not change '
                                                            'source-library authority beyond '
                                                            'deterministic selection/loading '
                                                            'behavior.\n'
                                                            '\n'
                                                            '## Validation Requirement\n'
                                                            '\n'
                                                            'Because M29.3 changes code, source '
                                                            'contracts, deterministic behavior, '
                                                            'and tests, validation requires:\n'
                                                            '\n'
                                                            '    python -m pytest -q\n'
                                                            '\n'
                                                            'Validation has not been executed by '
                                                            'this user-applied package record.\n'
                                                            '\n'
                                                            '## DDR Impact\n'
                                                            '\n'
                                                            '- DDR-003 is directly touched because '
                                                            'this package implements deterministic '
                                                            'template selection/loading over the '
                                                            'M29.2 template records.\n'
                                                            '- DDR-006 remains carried forward '
                                                            'because product-ready '
                                                            'document/export/report generation and '
                                                            'rendering are not implemented by '
                                                            'M29.3.\n'
                                                            '- DDR-005 remains deferred to M30; no '
                                                            'retrieval or embedding is '
                                                            'implemented.\n'
                                                            '\n'
                                                            '## Explicit Non-Implementation '
                                                            'Claims\n'
                                                            '\n'
                                                            'This M29.3 package does not:\n'
                                                            '\n'
                                                            '- validate final document input '
                                                            'schemas;\n'
                                                            '- implement DCF forms or extraction;\n'
                                                            '- implement controlled drafting '
                                                            'modes;\n'
                                                            '- generate product-ready documents;\n'
                                                            '- render, export, or report '
                                                            'documents;\n'
                                                            '- implement document lifecycle '
                                                            'persistence;\n'
                                                            '- implement review/approval runtime '
                                                            'workflow;\n'
                                                            '- implement UI/API behavior;\n'
                                                            '- implement AI/model/provider '
                                                            'behavior;\n'
                                                            '- authorize deployment, '
                                                            'productization, or SaaS readiness.\n'
                                                            '\n'
                                                            '## Tracker Movement Rule\n'
                                                            '\n'
                                                            '`PROGRESS_TRACKER.md` must not be '
                                                            'advanced until the package is applied '
                                                            'locally and `python -m pytest -q` is '
                                                            'run with truthful recorded validation '
                                                            'status.\n',
 'tests/test_template_selection.py': 'import pytest\n'
                                     '\n'
                                     'from asbp.document_template_store import '
                                     'load_default_document_template_library\n'
                                     'from asbp.template_selection import '
                                     'load_template_for_request, select_template_for_request\n'
                                     'from asbp.template_selection_model import '
                                     'TemplateSelectionInputModel\n'
                                     '\n'
                                     '\n'
                                     'def _required_non_implementation_claims() -> list[str]:\n'
                                     '    return [\n'
                                     '        "does_not_generate_documents",\n'
                                     '        "does_not_validate_document_input_schemas",\n'
                                     '        "does_not_render_or_export_documents",\n'
                                     '        "does_not_use_ai_to_choose_templates",\n'
                                     '    ]\n'
                                     '\n'
                                     '\n'
                                     'def _qp_request(**overrides) -> '
                                     'TemplateSelectionInputModel:\n'
                                     '    payload = {\n'
                                     '        "selection_id": "TPLSEL-QUALIFICATION-PLAN@v1",\n'
                                     '        "status": '
                                     '"deterministic_template_selection_request",\n'
                                     '        "document_family_id": "DOCF-PLAN-STRATEGY",\n'
                                     '        "document_type": "Qualification Plan",\n'
                                     '        "selector_context_ref": '
                                     '"SEL-PF-PROCESS-EQUIPMENT-INT-E2E-QUALIFICATION",\n'
                                     '        "profile_refs": '
                                     '["PROF-PROCESS-EQUIPMENT-GMP-BASELINE@v1"],\n'
                                     '        "standards_bundle_refs": ["SB-CQV-GMP@v1"],\n'
                                     '        "task_document_mapping_refs": '
                                     '["MAP-STD-CQV-GMP-TO-QP-TEMPLATE@v1"],\n'
                                     '        "intake_route_ref": "ROUTE-DCF",\n'
                                     '        "selection_controls": [\n'
                                     '            "Template selection must use deterministic '
                                     'source records only."\n'
                                     '        ],\n'
                                     '        "explicit_non_implementation_claims": '
                                     '_required_non_implementation_claims(),\n'
                                     '    }\n'
                                     '    payload.update(overrides)\n'
                                     '    return TemplateSelectionInputModel(**payload)\n'
                                     '\n'
                                     '\n'
                                     'def _csv_request(**overrides) -> '
                                     'TemplateSelectionInputModel:\n'
                                     '    payload = {\n'
                                     '        "selection_id": "TPLSEL-CSV-VALIDATION-PLAN@v1",\n'
                                     '        "status": '
                                     '"deterministic_template_selection_request",\n'
                                     '        "document_family_id": "DOCF-PLAN-STRATEGY",\n'
                                     '        "document_type": "CSV Validation Plan",\n'
                                     '        "selector_context_ref": '
                                     '"SEL-PF-COMPUTERIZED-SYSTEMS-INT-CSV",\n'
                                     '        "profile_refs": '
                                     '["PROF-COMPUTERIZED-SYSTEM-BASELINE@v1"],\n'
                                     '        "standards_bundle_refs": ["SB-CSV-GXP@v1"],\n'
                                     '        "task_document_mapping_refs": '
                                     '["MAP-STD-CSV-GXP-TO-CSV-TEMPLATE@v1"],\n'
                                     '        "intake_route_ref": "ROUTE-DCF",\n'
                                     '        "selection_controls": [\n'
                                     '            "Template selection must use deterministic '
                                     'source records only."\n'
                                     '        ],\n'
                                     '        "explicit_non_implementation_claims": '
                                     '_required_non_implementation_claims(),\n'
                                     '    }\n'
                                     '    payload.update(overrides)\n'
                                     '    return TemplateSelectionInputModel(**payload)\n'
                                     '\n'
                                     '\n'
                                     'def '
                                     'test_selects_qualification_plan_template_deterministically():\n'
                                     '    result = select_template_for_request(_qp_request())\n'
                                     '\n'
                                     '    assert result.status == "selected"\n'
                                     '    assert result.selected_template_id == '
                                     '"TPL-FUTURE-QUALIFICATION-PLAN@v1"\n'
                                     '    assert result.source_mapping_ids == '
                                     '["MAP-STD-CQV-GMP-TO-QP-TEMPLATE@v1"]\n'
                                     '\n'
                                     '\n'
                                     'def '
                                     'test_loads_selected_qualification_plan_template_record():\n'
                                     '    template = load_template_for_request(_qp_request())\n'
                                     '\n'
                                     '    assert template.template_id == '
                                     '"TPL-FUTURE-QUALIFICATION-PLAN@v1"\n'
                                     '    assert template.document_type == "Qualification Plan"\n'
                                     '    assert "SB-CQV-GMP@v1" in '
                                     'template.standards_bundle_refs\n'
                                     '\n'
                                     '\n'
                                     'def '
                                     'test_selects_csv_validation_plan_template_deterministically():\n'
                                     '    result = select_template_for_request(_csv_request())\n'
                                     '\n'
                                     '    assert result.status == "selected"\n'
                                     '    assert result.selected_template_id == '
                                     '"TPL-FUTURE-CSV-VALIDATION-PLAN@v1"\n'
                                     '    assert result.source_mapping_ids == '
                                     '["MAP-STD-CSV-GXP-TO-CSV-TEMPLATE@v1"]\n'
                                     '\n'
                                     '\n'
                                     'def '
                                     'test_selection_returns_no_match_for_unknown_document_type():\n'
                                     '    result = select_template_for_request(\n'
                                     '        _qp_request(\n'
                                     '            selection_id="TPLSEL-OQ-PROTOCOL@v1",\n'
                                     '            document_type="OQ Protocol",\n'
                                     '        )\n'
                                     '    )\n'
                                     '\n'
                                     '    assert result.status == "no_match"\n'
                                     '    assert result.selected_template_id is None\n'
                                     '    assert any(\n'
                                     '        rejection.reason_code == "document_type_mismatch"\n'
                                     '        for rejection in result.rejected_candidates\n'
                                     '    )\n'
                                     '\n'
                                     '\n'
                                     'def '
                                     'test_selection_returns_no_match_for_unsupported_standards_bundle():\n'
                                     '    result = select_template_for_request(\n'
                                     '        _qp_request(\n'
                                     '            standards_bundle_refs=["SB-UNSUPPORTED@v1"],\n'
                                     '            task_document_mapping_refs=[],\n'
                                     '        )\n'
                                     '    )\n'
                                     '\n'
                                     '    assert result.status == "no_match"\n'
                                     '    assert result.selected_template_id is None\n'
                                     '    assert any(\n'
                                     '        rejection.reason_code == '
                                     '"standards_bundle_mismatch"\n'
                                     '        for rejection in result.rejected_candidates\n'
                                     '    )\n'
                                     '\n'
                                     '\n'
                                     'def '
                                     'test_selection_returns_no_match_for_unsupported_template_intake_route():\n'
                                     '    library = load_default_document_template_library()\n'
                                     '    library.template_records[0].intake_route_refs = '
                                     '["ROUTE-DCF"]\n'
                                     '\n'
                                     '    result = select_template_for_request(\n'
                                     '        _qp_request(intake_route_ref="ROUTE-SKIP-DCF"),\n'
                                     '        template_library=library,\n'
                                     '    )\n'
                                     '\n'
                                     '    assert result.status == "no_match"\n'
                                     '    assert any(\n'
                                     '        rejection.reason_code == "intake_route_mismatch"\n'
                                     '        for rejection in result.rejected_candidates\n'
                                     '    )\n'
                                     '\n'
                                     '\n'
                                     'def test_selection_rejects_inactive_template_record():\n'
                                     '    library = load_default_document_template_library()\n'
                                     '    library.template_records[0].lifecycle_status = '
                                     '"retired"\n'
                                     '\n'
                                     '    result = select_template_for_request(_qp_request(), '
                                     'template_library=library)\n'
                                     '\n'
                                     '    assert result.status == "no_match"\n'
                                     '    assert any(\n'
                                     '        rejection.reason_code == '
                                     '"inactive_lifecycle_status"\n'
                                     '        for rejection in result.rejected_candidates\n'
                                     '    )\n'
                                     '\n'
                                     '\n'
                                     'def '
                                     'test_selection_returns_ambiguous_when_multiple_records_match_without_standard_filter():\n'
                                     '    library = load_default_document_template_library()\n'
                                     '    alternate = '
                                     'library.template_records[0].model_copy(deep=True)\n'
                                     '    alternate.template_id = "TPL-ALT-QUALIFICATION-PLAN@v1"\n'
                                     '    alternate.source_location = (\n'
                                     '        '
                                     '"data/source/document_templates/starter_document_templates.json::"\n'
                                     '        "TPL-ALT-QUALIFICATION-PLAN@v1"\n'
                                     '    )\n'
                                     '    library.template_records.append(alternate)\n'
                                     '\n'
                                     '    result = select_template_for_request(\n'
                                     '        _qp_request(standards_bundle_refs=[], '
                                     'task_document_mapping_refs=[]),\n'
                                     '        template_library=library,\n'
                                     '    )\n'
                                     '\n'
                                     '    assert result.status == "ambiguous"\n'
                                     '    assert sorted(result.candidate_template_ids) == [\n'
                                     '        "TPL-ALT-QUALIFICATION-PLAN@v1",\n'
                                     '        "TPL-FUTURE-QUALIFICATION-PLAN@v1",\n'
                                     '    ]\n'
                                     '\n'
                                     '\n'
                                     'def '
                                     'test_load_template_raises_when_selection_is_not_unique():\n'
                                     '    with pytest.raises(ValueError) as exc_info:\n'
                                     '        load_template_for_request(\n'
                                     '            _qp_request(\n'
                                     '                selection_id="TPLSEL-MISSING-TEMPLATE@v1",\n'
                                     '                document_type="Missing Template",\n'
                                     '            )\n'
                                     '        )\n'
                                     '\n'
                                     '    assert "did not resolve to exactly one template" in '
                                     'str(exc_info.value)\n',
 'tests/test_template_selection_model.py': 'import pytest\n'
                                           'from pydantic import ValidationError\n'
                                           '\n'
                                           'from asbp.template_selection_model import (\n'
                                           '    TemplateSelectionInputModel,\n'
                                           '    TemplateSelectionResultModel,\n'
                                           ')\n'
                                           '\n'
                                           '\n'
                                           'def _required_non_implementation_claims() -> '
                                           'list[str]:\n'
                                           '    return [\n'
                                           '        "does_not_generate_documents",\n'
                                           '        "does_not_validate_document_input_schemas",\n'
                                           '        "does_not_render_or_export_documents",\n'
                                           '        "does_not_use_ai_to_choose_templates",\n'
                                           '    ]\n'
                                           '\n'
                                           '\n'
                                           'def _minimal_selection_payload() -> dict:\n'
                                           '    return {\n'
                                           '        "selection_id": '
                                           '"TPLSEL-QUALIFICATION-PLAN@v1",\n'
                                           '        "status": '
                                           '"deterministic_template_selection_request",\n'
                                           '        "document_family_id": "DOCF-PLAN-STRATEGY",\n'
                                           '        "document_type": "Qualification Plan",\n'
                                           '        "template_intent": "Qualification strategy '
                                           'planning",\n'
                                           '        "selector_context_ref": '
                                           '"SEL-PF-PROCESS-EQUIPMENT-INT-E2E-QUALIFICATION",\n'
                                           '        "profile_refs": '
                                           '["PROF-PROCESS-EQUIPMENT-GMP-BASELINE@v1"],\n'
                                           '        "standards_bundle_refs": ["SB-CQV-GMP@v1"],\n'
                                           '        "task_document_mapping_refs": '
                                           '["MAP-STD-CQV-GMP-TO-QP-TEMPLATE@v1"],\n'
                                           '        "intake_route_ref": "ROUTE-DCF",\n'
                                           '        "selection_controls": [\n'
                                           '            "Template selection must use deterministic '
                                           'source records only."\n'
                                           '        ],\n'
                                           '        "explicit_non_implementation_claims": '
                                           '_required_non_implementation_claims(),\n'
                                           '    }\n'
                                           '\n'
                                           '\n'
                                           'def '
                                           'test_template_selection_input_accepts_controlled_minimum():\n'
                                           '    request = '
                                           'TemplateSelectionInputModel(**_minimal_selection_payload())\n'
                                           '\n'
                                           '    assert request.selection_id == '
                                           '"TPLSEL-QUALIFICATION-PLAN@v1"\n'
                                           '    assert request.document_family_id == '
                                           '"DOCF-PLAN-STRATEGY"\n'
                                           '    assert request.standards_bundle_refs == '
                                           '["SB-CQV-GMP@v1"]\n'
                                           '\n'
                                           '\n'
                                           'def '
                                           'test_template_selection_input_rejects_unsupported_intake_route():\n'
                                           '    payload = _minimal_selection_payload()\n'
                                           '    payload["intake_route_ref"] = '
                                           '"ROUTE-UNCONTROLLED"\n'
                                           '\n'
                                           '    with pytest.raises(ValidationError) as exc_info:\n'
                                           '        TemplateSelectionInputModel(**payload)\n'
                                           '\n'
                                           '    assert "Input should be" in str(exc_info.value)\n'
                                           '\n'
                                           '\n'
                                           'def '
                                           'test_template_selection_input_rejects_invalid_standard_bundle_ref():\n'
                                           '    payload = _minimal_selection_payload()\n'
                                           '    payload["standards_bundle_refs"] = '
                                           '["STD-CQV-GMP"]\n'
                                           '\n'
                                           '    with pytest.raises(ValidationError) as exc_info:\n'
                                           '        TemplateSelectionInputModel(**payload)\n'
                                           '\n'
                                           '    assert "standards_bundle_refs must use '
                                           'SB-...@v..." in str(exc_info.value)\n'
                                           '\n'
                                           '\n'
                                           'def '
                                           'test_template_selection_input_requires_explicit_non_implementation_claims():\n'
                                           '    payload = _minimal_selection_payload()\n'
                                           '    payload["explicit_non_implementation_claims"] = '
                                           '["does_not_generate_documents"]\n'
                                           '\n'
                                           '    with pytest.raises(ValidationError) as exc_info:\n'
                                           '        TemplateSelectionInputModel(**payload)\n'
                                           '\n'
                                           '    assert "M29.3 template selection request is '
                                           'missing explicit" in str(exc_info.value)\n'
                                           '\n'
                                           '\n'
                                           'def '
                                           'test_template_selection_result_requires_selected_template_for_selected_status():\n'
                                           '    with pytest.raises(ValidationError) as exc_info:\n'
                                           '        TemplateSelectionResultModel(\n'
                                           '            '
                                           'selection_id="TPLSEL-QUALIFICATION-PLAN@v1",\n'
                                           '            status="selected",\n'
                                           '            '
                                           'candidate_template_ids=["TPL-FUTURE-QUALIFICATION-PLAN@v1"],\n'
                                           '            decision_reason="Selected '
                                           'deterministically.",\n'
                                           '            '
                                           'explicit_non_implementation_claims=_required_non_implementation_claims(),\n'
                                           '        )\n'
                                           '\n'
                                           '    assert "requires selected_template_id" in '
                                           'str(exc_info.value)\n'
                                           '\n'
                                           '\n'
                                           'def '
                                           'test_template_selection_result_rejects_selected_template_for_no_match_status():\n'
                                           '    with pytest.raises(ValidationError) as exc_info:\n'
                                           '        TemplateSelectionResultModel(\n'
                                           '            '
                                           'selection_id="TPLSEL-QUALIFICATION-PLAN@v1",\n'
                                           '            status="no_match",\n'
                                           '            '
                                           'selected_template_id="TPL-FUTURE-QUALIFICATION-PLAN@v1",\n'
                                           '            candidate_template_ids=[],\n'
                                           '            decision_reason="No match.",\n'
                                           '            '
                                           'explicit_non_implementation_claims=_required_non_implementation_claims(),\n'
                                           '        )\n'
                                           '\n'
                                           '    assert "cannot include selected_template_id" in '
                                           'str(exc_info.value)\n'
                                           '\n'
                                           '\n'
                                           'def '
                                           'test_persisted_state_payload_is_not_template_selection_truth():\n'
                                           '    persisted_state_payload = {\n'
                                           '        "project": "AI_SYSTEM_BUILDER",\n'
                                           '        "version": "0.8.0",\n'
                                           '        "status": "in_flight",\n'
                                           '        "tasks": [],\n'
                                           '    }\n'
                                           '\n'
                                           '    with pytest.raises(ValidationError):\n'
                                           '        '
                                           'TemplateSelectionInputModel(**persisted_state_payload)\n'}


def main() -> None:
    repo_root = Path.cwd()
    if not (repo_root / "ROADMAP_CANONICAL.md").exists() or not (repo_root / "asbp").is_dir():
        raise SystemExit("Run this apply.py from the AI_SYSTEM_BUILDER repository root.")

    written: list[str] = []
    for relative_path, content in FILES.items():
        target = repo_root / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(relative_path)

    print("M29.3 template selection/loading package applied.")
    print("Files written:")
    for path in written:
        print(f"- {path}")
    print("\nNext required validation:")
    print("python -m pytest -q")


if __name__ == "__main__":
    main()
