"""UI product-surface boundary package.

The UI layer is a downstream product surface and visibility adapter only.
It must consume API/service boundaries and must not own domain logic,
validation truth, execution truth, source truth, or raw persistence access.
"""

from .boundary import UI_BOUNDARY_CONTRACT, UiBoundaryContract, get_ui_boundary_contract
from .document_output_visibility import (
    ALLOWED_UI_DOCUMENT_OUTPUT_SOURCE_BOUNDARIES,
    FORBIDDEN_UI_DOCUMENT_OUTPUT_SOURCE_BOUNDARIES,
    SUPPORTED_UI_DOCUMENT_OUTPUT_VISIBILITY_SURFACES,
    UI_DOCUMENT_OUTPUT_VISIBILITY_SURFACE_CONTRACTS,
    UiDocumentOutputKind,
    UiDocumentOutputStatus,
    UiDocumentOutputVisibilityPayload,
    UiDocumentOutputVisibilitySurfaceContract,
    UiDocumentOutputVisibilitySurfaceName,
    build_ui_document_output_visibility_payload,
    get_ui_document_output_visibility_surface_contract,
    list_ui_document_output_visibility_surface_contracts,
    normalize_ui_document_output_kind,
    normalize_ui_document_output_source_boundary,
    normalize_ui_document_output_status,
    normalize_ui_document_output_visibility_surface,
)
from .interaction_flow import (
    SUPPORTED_UI_INTERACTION_FLOWS,
    UI_INTERACTION_FLOW_CONTRACTS,
    UiActionIntakeDecision,
    UiActionIntakeDecisionResult,
    UiActionIntakeRequest,
    UiInteractionFlowContract,
    UiInteractionFlowName,
    UiInteractionMode,
    build_ui_action_intake_request,
    evaluate_ui_action_intake,
    get_ui_interaction_flow_contract,
    list_ui_interaction_flow_contracts,
    normalize_ui_interaction_flow,
    normalize_ui_interaction_mode,
)
from .workflow_visibility import (
    ALLOWED_UI_WORKFLOW_VISIBILITY_SOURCE_BOUNDARIES,
    FORBIDDEN_UI_WORKFLOW_VISIBILITY_SOURCE_BOUNDARIES,
    SUPPORTED_UI_WORKFLOW_VISIBILITY_SURFACES,
    UI_WORKFLOW_VISIBILITY_SURFACE_CONTRACTS,
    UiWorkflowVisibilityPayload,
    UiWorkflowVisibilitySurfaceContract,
    UiWorkflowVisibilitySurfaceName,
    build_ui_workflow_visibility_payload,
    get_ui_workflow_visibility_surface_contract,
    list_ui_workflow_visibility_surface_contracts,
    normalize_ui_workflow_visibility_source_boundary,
    normalize_ui_workflow_visibility_surface,
)

__all__ = [
    "ALLOWED_UI_DOCUMENT_OUTPUT_SOURCE_BOUNDARIES",
    "ALLOWED_UI_WORKFLOW_VISIBILITY_SOURCE_BOUNDARIES",
    "FORBIDDEN_UI_DOCUMENT_OUTPUT_SOURCE_BOUNDARIES",
    "FORBIDDEN_UI_WORKFLOW_VISIBILITY_SOURCE_BOUNDARIES",
    "SUPPORTED_UI_DOCUMENT_OUTPUT_VISIBILITY_SURFACES",
    "SUPPORTED_UI_INTERACTION_FLOWS",
    "SUPPORTED_UI_WORKFLOW_VISIBILITY_SURFACES",
    "UI_BOUNDARY_CONTRACT",
    "UI_DOCUMENT_OUTPUT_VISIBILITY_SURFACE_CONTRACTS",
    "UI_INTERACTION_FLOW_CONTRACTS",
    "UI_WORKFLOW_VISIBILITY_SURFACE_CONTRACTS",
    "UiActionIntakeDecision",
    "UiActionIntakeDecisionResult",
    "UiActionIntakeRequest",
    "UiBoundaryContract",
    "UiDocumentOutputKind",
    "UiDocumentOutputStatus",
    "UiDocumentOutputVisibilityPayload",
    "UiDocumentOutputVisibilitySurfaceContract",
    "UiDocumentOutputVisibilitySurfaceName",
    "UiInteractionFlowContract",
    "UiInteractionFlowName",
    "UiInteractionMode",
    "UiWorkflowVisibilityPayload",
    "UiWorkflowVisibilitySurfaceContract",
    "UiWorkflowVisibilitySurfaceName",
    "build_ui_action_intake_request",
    "build_ui_document_output_visibility_payload",
    "build_ui_workflow_visibility_payload",
    "evaluate_ui_action_intake",
    "get_ui_boundary_contract",
    "get_ui_document_output_visibility_surface_contract",
    "get_ui_interaction_flow_contract",
    "get_ui_workflow_visibility_surface_contract",
    "list_ui_document_output_visibility_surface_contracts",
    "list_ui_interaction_flow_contracts",
    "list_ui_workflow_visibility_surface_contracts",
    "normalize_ui_document_output_kind",
    "normalize_ui_document_output_source_boundary",
    "normalize_ui_document_output_status",
    "normalize_ui_document_output_visibility_surface",
    "normalize_ui_interaction_flow",
    "normalize_ui_interaction_mode",
    "normalize_ui_workflow_visibility_source_boundary",
    "normalize_ui_workflow_visibility_surface",
]
