"""Shared external-surface contract discipline for ASBP.

The external-surface layer aligns API and UI contract vocabulary only.
It must not own domain logic, validation truth, execution truth, source truth,
raw state access, raw persistence access, deployment behavior, or
productization behavior.
"""

from .acceptance import (
    EXPECTED_PHASE_7_CLOSEOUT_EVIDENCE,
    EXPECTED_UAT_EVIDENCE_CATEGORIES,
    EXPECTED_VALIDATION_EVIDENCE_CATEGORIES,
    FORBIDDEN_ACCEPTANCE_ASSUMPTIONS,
    AcceptanceDecision,
    ExternalSurfaceAcceptanceDiscipline,
    ExternalSurfaceAcceptanceEvidenceCategory,
    ExternalSurfaceAcceptanceReadinessDecision,
    ExternalSurfaceAcceptanceReadinessResult,
    build_external_surface_acceptance_discipline,
    evaluate_external_surface_acceptance_readiness,
    get_expected_phase_7_closeout_evidence,
    get_expected_uat_evidence_categories,
    get_expected_validation_evidence_categories,
    normalize_acceptance_decision,
    normalize_acceptance_evidence_category,
)
from .boundary import (
    EXTERNAL_SURFACE_BOUNDARY_CONTRACT,
    ExternalSurfaceBoundaryContract,
    get_external_surface_boundary_contract,
)
from .consistency import (
    FORBIDDEN_UI_API_CONSISTENCY_BEHAVIORS,
    SUPPORTED_UI_API_CONSISTENCY_RULES,
    OperatorVisibleState,
    UiApiConsistencyDecision,
    UiApiConsistencyResult,
    UiApiConsistencyRule,
    evaluate_ui_api_consistency,
    get_ui_api_consistency_rule,
    list_ui_api_consistency_rules,
    normalize_operator_visible_state,
)
from .contracts import (
    FORBIDDEN_EXTERNAL_AUTHORITY_CLAIMS,
    FORBIDDEN_EXTERNAL_BEHAVIORS,
    SUPPORTED_EXTERNAL_CONTRACT_FIELDS,
    SUPPORTED_EXTERNAL_SURFACE_CHANNELS,
    SUPPORTED_EXTERNAL_SURFACE_ROLES,
    ExternalContractCompatibilityDecision,
    ExternalContractCompatibilityResult,
    ExternalContractDiscipline,
    ExternalContractField,
    ExternalSurfaceChannel,
    ExternalSurfaceRole,
    build_external_contract_discipline,
    evaluate_external_contract_compatibility,
    get_supported_external_contract_fields,
    normalize_external_contract_field,
    normalize_external_surface_channel,
    normalize_external_surface_role,
)
from .governance import (
    FORBIDDEN_PRODUCT_SURFACE_BEHAVIORS,
    SUPPORTED_PRODUCT_SURFACE_CAPABILITIES,
    SUPPORTED_PRODUCT_SURFACE_EXPOSURES,
    SUPPORTED_PRODUCT_SURFACE_GOVERNANCE_RULES,
    ProductSurfaceCapability,
    ProductSurfaceExposure,
    ProductSurfaceGovernanceDecision,
    ProductSurfaceGovernanceResult,
    ProductSurfaceGovernanceRule,
    evaluate_product_surface_governance,
    get_product_surface_governance_rule,
    list_product_surface_governance_rules,
    normalize_product_surface_capability,
    normalize_product_surface_exposure,
)

__all__ = [
    "EXPECTED_PHASE_7_CLOSEOUT_EVIDENCE",
    "EXPECTED_UAT_EVIDENCE_CATEGORIES",
    "EXPECTED_VALIDATION_EVIDENCE_CATEGORIES",
    "EXTERNAL_SURFACE_BOUNDARY_CONTRACT",
    "FORBIDDEN_ACCEPTANCE_ASSUMPTIONS",
    "FORBIDDEN_EXTERNAL_AUTHORITY_CLAIMS",
    "FORBIDDEN_EXTERNAL_BEHAVIORS",
    "FORBIDDEN_PRODUCT_SURFACE_BEHAVIORS",
    "FORBIDDEN_UI_API_CONSISTENCY_BEHAVIORS",
    "SUPPORTED_EXTERNAL_CONTRACT_FIELDS",
    "SUPPORTED_EXTERNAL_SURFACE_CHANNELS",
    "SUPPORTED_EXTERNAL_SURFACE_ROLES",
    "SUPPORTED_PRODUCT_SURFACE_CAPABILITIES",
    "SUPPORTED_PRODUCT_SURFACE_EXPOSURES",
    "SUPPORTED_PRODUCT_SURFACE_GOVERNANCE_RULES",
    "SUPPORTED_UI_API_CONSISTENCY_RULES",
    "AcceptanceDecision",
    "ExternalContractCompatibilityDecision",
    "ExternalContractCompatibilityResult",
    "ExternalContractDiscipline",
    "ExternalContractField",
    "ExternalSurfaceAcceptanceDiscipline",
    "ExternalSurfaceAcceptanceEvidenceCategory",
    "ExternalSurfaceAcceptanceReadinessDecision",
    "ExternalSurfaceAcceptanceReadinessResult",
    "ExternalSurfaceBoundaryContract",
    "ExternalSurfaceChannel",
    "ExternalSurfaceRole",
    "OperatorVisibleState",
    "ProductSurfaceCapability",
    "ProductSurfaceExposure",
    "ProductSurfaceGovernanceDecision",
    "ProductSurfaceGovernanceResult",
    "ProductSurfaceGovernanceRule",
    "UiApiConsistencyDecision",
    "UiApiConsistencyResult",
    "UiApiConsistencyRule",
    "build_external_contract_discipline",
    "build_external_surface_acceptance_discipline",
    "evaluate_external_contract_compatibility",
    "evaluate_external_surface_acceptance_readiness",
    "evaluate_product_surface_governance",
    "evaluate_ui_api_consistency",
    "get_expected_phase_7_closeout_evidence",
    "get_expected_uat_evidence_categories",
    "get_expected_validation_evidence_categories",
    "get_external_surface_boundary_contract",
    "get_product_surface_governance_rule",
    "get_supported_external_contract_fields",
    "get_ui_api_consistency_rule",
    "list_product_surface_governance_rules",
    "list_ui_api_consistency_rules",
    "normalize_acceptance_decision",
    "normalize_acceptance_evidence_category",
    "normalize_external_contract_field",
    "normalize_external_surface_channel",
    "normalize_external_surface_role",
    "normalize_operator_visible_state",
    "normalize_product_surface_capability",
    "normalize_product_surface_exposure",
]
