"""Read-only local workflow output review/access logic for M32.6.

This module builds bounded output review payloads from validated state and
approved output visibility models. It does not generate documents, create
exports, mutate lifecycle/review state, or claim output acceptance.
"""

from __future__ import annotations

from typing import Any

from asbp.core.work_packages import find_work_package_by_id
from asbp.document_lifecycle_model import DocumentLifecycleRecordModel
from asbp.local_workflow_logic import LOCAL_WORKFLOW_SURFACE
from asbp.output_validation_model import OutputValidationResultModel
from asbp.renderer_output_model import RendererArtifactMetadataModel
from asbp.state_model import StateModel
from asbp.ui.document_output_visibility import build_ui_document_output_visibility_payload

LOCAL_WORKFLOW_OUTPUT_CHECKPOINT = "M32.6 — Output review/download surfaces"

OUTPUT_REVIEW_LIMITATIONS = [
    "CLI/local workflow surface is an adapter only.",
    "This outputs command is read-only and does not mutate state.",
    "No document, export, report, or rendered artifact is generated by this surface.",
    "Artifact access is metadata/reference-only unless separately scoped.",
    "No output is silently accepted, approved, signed, released, or certified.",
    "Generated or assembled output remains human-review-required.",
    "This is not release, deployment, SaaS, commercial, or customer-ready evidence.",
]


def _empty_artifact_metadata() -> dict[str, Any]:
    return {
        "artifact_available": False,
        "artifact_id": None,
        "artifact_filename": None,
        "output_format": None,
        "media_type": None,
        "source_draft_id": None,
        "template_id": None,
        "schema_id": None,
        "standards_control_packet_id": None,
        "placeholder_present": None,
        "limitation_present": None,
        "standards_warning_present": None,
        "non_product_ready": True,
    }


def _artifact_metadata_payload(
    artifact_metadata: RendererArtifactMetadataModel | None,
) -> dict[str, Any]:
    if artifact_metadata is None:
        return _empty_artifact_metadata()

    return {
        "artifact_available": True,
        "artifact_id": artifact_metadata.artifact_id,
        "artifact_filename": artifact_metadata.artifact_filename,
        "output_format": artifact_metadata.output_format,
        "media_type": artifact_metadata.media_type,
        "source_draft_id": artifact_metadata.source_draft_id,
        "template_id": artifact_metadata.template_id,
        "schema_id": artifact_metadata.schema_id,
        "standards_control_packet_id": artifact_metadata.standards_control_packet_id,
        "placeholder_present": artifact_metadata.placeholder_present,
        "limitation_present": artifact_metadata.limitation_present,
        "standards_warning_present": artifact_metadata.standards_warning_present,
        "non_product_ready": artifact_metadata.non_product_ready,
    }


def _build_visibility_payload(
    *,
    surface_name: str,
    output_kind: str,
    output_status: str,
    artifact_metadata: RendererArtifactMetadataModel | None,
) -> dict[str, Any]:
    display_payload: dict[str, Any] = {
        "output_status": output_status,
        "artifact_available": artifact_metadata is not None,
    }
    metadata_payload: dict[str, Any] = {
        "visibility_only": True,
        "generation_allowed": False,
        "approval_claimed": False,
        "release_claimed": False,
    }

    if artifact_metadata is not None:
        display_payload.update(
            {
                "artifact_id": artifact_metadata.artifact_id,
                "artifact_filename": artifact_metadata.artifact_filename,
                "output_format": artifact_metadata.output_format,
            }
        )
        metadata_payload.update(
            {
                "non_product_ready": artifact_metadata.non_product_ready,
                "limitation_present": artifact_metadata.limitation_present,
                "standards_warning_present": artifact_metadata.standards_warning_present,
            }
        )

    source_boundary = (
        "output_target_metadata"
        if surface_name == "output_target_status"
        else "approved_output_boundary"
    )

    return build_ui_document_output_visibility_payload(
        surface_name=surface_name,
        source_boundary=source_boundary,
        output_kind=output_kind,
        output_status=output_status,
        display_payload=display_payload,
        metadata=metadata_payload,
    ).to_dict()


def _build_document_export_view(
    artifact_metadata: RendererArtifactMetadataModel | None,
) -> dict[str, Any]:
    document_status = "available" if artifact_metadata is not None else "not_available"
    export_status = (
        "available"
        if artifact_metadata is not None
        and artifact_metadata.output_format == "csv_summary"
        else "not_available"
    )
    output_target_status = "available" if artifact_metadata is not None else "not_available"

    visibility_payloads = [
        _build_visibility_payload(
            surface_name="output_target_status",
            output_kind="output_target",
            output_status=output_target_status,
            artifact_metadata=artifact_metadata,
        ),
        _build_visibility_payload(
            surface_name="document_output_status",
            output_kind="document",
            output_status=document_status,
            artifact_metadata=artifact_metadata,
        ),
        _build_visibility_payload(
            surface_name="export_output_status",
            output_kind="export",
            output_status=export_status,
            artifact_metadata=artifact_metadata,
        ),
        _build_visibility_payload(
            surface_name="reporting_output_status",
            output_kind="report",
            output_status="not_available",
            artifact_metadata=None,
        ),
    ]

    return {
        "output_target_status": output_target_status,
        "document_output_status": document_status,
        "export_output_status": export_status,
        "reporting_output_status": "not_available",
        "visibility_payloads": visibility_payloads,
    }


def _build_validation_state(
    output_validation_result: OutputValidationResultModel | None,
) -> dict[str, Any]:
    if output_validation_result is None:
        return {
            "validation_available": False,
            "validation_id": None,
            "status": "not_available",
            "checks_performed": [],
            "issues": [],
        }

    return {
        "validation_available": True,
        "validation_id": output_validation_result.validation_id,
        "status": output_validation_result.status,
        "checks_performed": list(output_validation_result.checks_performed),
        "issues": [issue.model_dump() for issue in output_validation_result.issues],
    }


def _build_validation_limitations(
    *,
    artifact_metadata: RendererArtifactMetadataModel | None,
    output_validation_result: OutputValidationResultModel | None,
) -> list[str]:
    limitations: list[str] = []

    if artifact_metadata is None:
        limitations.append(
            "No output artifact metadata is available for this work package."
        )
    else:
        limitations.append(
            "Artifact metadata is visible only; this surface does not verify file existence or create downloads."
        )

    if output_validation_result is None:
        limitations.append(
            "No output validation result is available for this work package."
        )
    else:
        limitations.append(
            "Output validation result is visible only and does not approve, sign, release, or certify output."
        )

    limitations.append(
        "Output review surface does not approve, sign, release, or certify artifacts."
    )
    limitations.append(
        "Download/access remains metadata-reference-only unless a separately scoped safe artifact access path exists."
    )
    return limitations


def _build_review_acceptance_status(
    lifecycle_record: DocumentLifecycleRecordModel | None,
) -> dict[str, Any]:
    if lifecycle_record is None:
        return {
            "lifecycle_record_available": False,
            "lifecycle_record_id": None,
            "lifecycle_state": "not_available",
            "human_review_required": True,
            "accepted": False,
            "approval_claimed": False,
            "release_claimed": False,
        }

    review_obligations = [
        obligation.model_dump()
        for obligation in lifecycle_record.review_obligations
    ]
    approval_obligations = [
        obligation.model_dump()
        for obligation in lifecycle_record.approval_obligations
    ]

    return {
        "lifecycle_record_available": True,
        "lifecycle_record_id": lifecycle_record.lifecycle_record_id,
        "lifecycle_state": lifecycle_record.lifecycle_state,
        "human_review_required": True,
        "accepted": False,
        "approval_claimed": False,
        "release_claimed": False,
        "review_obligations": review_obligations,
        "approval_obligations": approval_obligations,
    }


def _build_safe_artifact_access(
    artifact_metadata: RendererArtifactMetadataModel | None,
) -> dict[str, Any]:
    if artifact_metadata is None:
        return {
            "access_available": False,
            "access_mode": "not_available",
            "artifact_reference": None,
            "download_allowed": False,
            "download_performed": False,
            "path_exposed": False,
        }

    return {
        "access_available": True,
        "access_mode": "metadata_reference_only",
        "artifact_reference": artifact_metadata.artifact_filename,
        "download_allowed": False,
        "download_performed": False,
        "path_exposed": False,
    }


def build_local_workflow_output_payload(
    state: StateModel,
    *,
    wp_id: str,
    artifact_metadata: RendererArtifactMetadataModel | None = None,
    output_validation_result: OutputValidationResultModel | None = None,
    lifecycle_record: DocumentLifecycleRecordModel | None = None,
) -> dict[str, Any]:
    """Build a read-only output review/access payload for a work package."""

    work_package = find_work_package_by_id(state.work_packages, wp_id)
    if work_package is None:
        raise ValueError(f"Work Package not found: {wp_id}")

    return {
        "checkpoint": LOCAL_WORKFLOW_OUTPUT_CHECKPOINT,
        "surface": LOCAL_WORKFLOW_SURFACE,
        "adapter_boundary": "CLI adapter reads validated state and approved output visibility boundaries only.",
        "selected_work_package": {
            "wp_id": work_package.wp_id,
            "title": work_package.title,
            "status": work_package.status,
        },
        "document_export_view": _build_document_export_view(artifact_metadata),
        "artifact_metadata": _artifact_metadata_payload(artifact_metadata),
        "output_validation_state": _build_validation_state(output_validation_result),
        "validation_limitations": _build_validation_limitations(
            artifact_metadata=artifact_metadata,
            output_validation_result=output_validation_result,
        ),
        "review_acceptance_status": _build_review_acceptance_status(lifecycle_record),
        "safe_artifact_access": _build_safe_artifact_access(artifact_metadata),
        "limitations": list(OUTPUT_REVIEW_LIMITATIONS),
        "next_safe_actions": [
            "Keep output review human-controlled before acceptance claims.",
            "Use later M32 checkpoints for failure handling and end-to-end scenario evidence.",
            "Do not treat metadata visibility as product-ready output or release evidence.",
        ],
    }
